#!/usr/bin/env php
<?php

require dirname(__DIR__) . DIRECTORY_SEPARATOR . 'constants' . DIRECTORY_SEPARATOR . 'common.php';
require dirname(__DIR__) . DS . 'constants' . DS . 'console.php';

require dirname(__DIR__) . DS . 'vendor' . DS . 'autoload.php';
require dirname(__DIR__) . DS . 'vendor' . DS .'yiisoft' . DS . 'yii2' . DS . 'Yii.php';

$config      = require dirname(__DIR__) . DS . APANEL_DIR . DS . 'config' . DS . 'console.php';
$application = new yii\console\Application($config);
$exitCode    = $application->run();

exit($exitCode);


function e($data='')
{
    echo '<pre>';
        var_dump($data);
    echo '</pre>';
}

